name: schedule trigger

on:
  schedule:
    - cron: '* * * * *'

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: echo current time of server
        run: echo "The current time of server is $(date)"
